# Generated by Django 3.0.3 on 2020-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_GET', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_cal', models.CharField(max_length=211111111111)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
